# Generated by Django 2.0.4 on 2018-04-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20180421_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_favarite',
            field=models.BooleanField(default=False),
        ),
    ]
