# Generated by Django 2.0.4 on 2018-04-22 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_is_favarite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='is_favarite',
            new_name='is_favorite',
        ),
    ]
